#!/bin/bash
sudo pacman -S --needed --noconfirm wget nasm qemu-headless gdb hexdump
wget https://raw.githubusercontent.com/Kris030/lowlew-basics/master/02_asm/compile
wget https://raw.githubusercontent.com/Kris030/lowlew-basics/master/02_asm/run
wget https://raw.githubusercontent.com/Kris030/lowlew-basics/master/02_asm/debug
wget https://raw.githubusercontent.com/Kris030/lowlew-basics/master/02_asm/run_gdb
echo 'Setup done.'
